version: '2'
services:
  web:
    build: ./phpserver
    ports:
      - "8000:80"
      - "3000"
      - "22"
    environment:
     - MYSQL_SERVER=mysql
    depends_on:
      - selenium-chrome
      - selenium-chrome-debug
    volumes:
      - ./phpserver/:/var/www/html/

  selenium-chrome:
    image: selenium/standalone-chrome:3.4.0-chromium
    ports:
      - "4444"
    volumes:
      - /dev/shm:/dev/shm
      
  selenium-chrome-debug:
    image: selenium/standalone-chrome-debug:3.4.0-chromium
    ports:
      - "4444"
      - "5900"
    volumes:
      - /dev/shm:/dev/shm

  nginx:
    build:
      context: ./nginx
    image: reactjs_nginx
    container_name: reactjs_nginx_container
    ports:
      - "8080:8080"
    volumes:
      - ./app/dist:/wwwroot:ro
  webpack:
    build:
      context: ./webpack
    image: reactjs_webpack
    container_name: reactjs_webpack_container
    volumes:
      - ./app/src:/app/src:ro
      - ./app/dist:/app/dist:z
  jenkins:
    image: 'jenkins:2.60.3'
    volumes:
      - jenkins-data:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=jenkins.local
      - VIRTUAL_PORT=8080
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
  ngnix-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
    jenkins-data:
        driver: local